name: Build and test

on:
  workflow_dispatch:
  pull_request:

# Test all inputs
# TODO: ensure that the output matches
# TODO: add failing cases
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "build"
        run: |
          npm install
          npm run build 
      - uses: ./ # local action in repo
        with:
          tool: 'cargo'
          platform: 'default'
          output-file-path: ./test/data/extract/cargo_output.txt
          data-out-path: output.txt
      - uses: ./ # local action in repo
        with:
          tool: 'cargo'
          platform: 'default'
          output-file-path: ./test/data/extract/cargo_output2.txt
          data-out-path: output.txt
      - uses: ./ # local action in repo
        with:
          tool: 'cargo'
          platform: 'default'
          output-file-path: ./test/data/extract/cargo_output3.txt
          data-out-path: output.txt
      - uses: ./ # local action in repo
        with:
          tool: 'cargo'
          platform: 'default'
          output-file-path: ./test/data/extract/criterion_output.txt
          data-out-path: output.txt
