name: Format and lint

on:
  workflow_dispatch:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "install and check format"
        run: |
          npm install
          npm run format:check 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "install and lint"
        run: |
          npm install
          npm run lint
