name: Example for minimal setup

on:
  workflow_dispatch:
  pull_request:

jobs:
  minimal-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "build"
        run: |
          npm install
          npm run build 
      - uses: ./ # local action in repo
        with:
          tool: 'cargo'
          os: 'ubuntu-latest'
          output-file-path: ./test/data/extract/cargo_output.txt
          data-out-path: output.json
