name: Example for minimal setup

on:
  workflow_dispatch:
  pull_request:

jobs:
  benchmark:
    name: Run minimal steps to run benchmark-data-extract-transform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./action # local action in repo
        with:
          tool: 'cargo'
          platform: 'default'
          output-file-path: test/data/cargo_output.txt
          json-out-path: output.txt
