name: Example for minimal setup

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run minimal steps to run benchmark-data-extract-transform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
